//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-1LO8U7LN\\SQLEXPRESS;Initial Catalog=DOANPTPMUNGDUNGTHONGMINH_Q" +
            "UANLYCUAHANGDIENMAY;User ID=sa;Password=nguyen114814")]
        public string DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString {
            get {
                return ((string)(this["DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QNConnection {
            get {
                return ((string)(this["QNConnection"]));
            }
            set {
                this["QNConnection"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-M1FML9B\\SQLEXPRESS;Initial Catalog=DOANPTPMUNGDUNGTHONGMINH_Q" +
            "UANLYCUAHANGDIENMAY;Integrated Security=True")]
        public string DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString1 {
            get {
                return ((string)(this["DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-M1FML9B\\SQLEXPRESS;Initial Catalog=DOANPTPMUNGDUNGTHONGMINH_Q" +
            "UANLYCUAHANGDIENMAY;Persist Security Info=True;User ID=sa;Password=20052000")]
        public string DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString2 {
            get {
                return ((string)(this["DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-1LO8U7LN\\SQLEXPRESS;Initial Catalog=DOANPTPMUNGDUNGTHONGMINH_Q" +
            "UANLYCUAHANGDIENMAY;Persist Security Info=True;User ID=sa;Password=nguyen114814")]
        public string DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString3 {
            get {
                return ((string)(this["DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-M1FML9B\\SQLEXPRESS;Initial Catalog=DOANPTPMUNGDUNGTHONGMINH_Q" +
            "UANLYCUAHANGDIENMAY;User ID=sa;Password=20052000")]
        public string DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString4 {
            get {
                return ((string)(this["DOANPTPMUNGDUNGTHONGMINH_QUANLYCUAHANGDIENMAYConnectionString4"]));
            }
        }
    }
}
